#!/bin/sh

set_wallpaper &
dwm_bar &
# xcompmgr &
picom --config ~/.config/picom.conf &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
dunst &
xset r rate 300 50 &
sxhkd &
xmodmap ~/.config/xmodmap/Xmodmap &
unclutter &

exec dwm > /dev/null 2>&1
